version: '3'

services: 
    backend:
        build: 
            context: ./backend
        command: gunicorn dictionaryapp.wsgi --bind 0.0.0.0:8000
        ports: 
            - 8000:8000
        volumes: 
            - django_static:/django/static
        
    frontend:
        build: 
            context: ./frontend
        volumes: 
            - react_build:/react/build
        # expose: 
        #     - 3000
        command: serve -s build -l 3000
        ports: 
            - 3000:3000
        
    nginx:
        build: ./nginx
        ports: 
            - 80:8080
        volumes: 
            - react_build:/var/www/react
        # depends_on: 
        #     - frontend

volumes: 
    react_build:
    django_static:
